//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeePass.I18n {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeePass.I18n.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///Developer&apos;s Blog (News &amp; Feedback): ähnelt.
        /// </summary>
        public static string About_Blog {
            get {
                return ResourceManager.GetString("About_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///Libraries used/referenced: ähnelt.
        /// </summary>
        public static string About_Libraries {
            get {
                return ResourceManager.GetString("About_Libraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die about ähnelt.
        /// </summary>
        public static string About_PageTitle {
            get {
                return ResourceManager.GetString("About_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Purchase ähnelt.
        /// </summary>
        public static string About_Purchase {
            get {
                return ResourceManager.GetString("About_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Review ähnelt.
        /// </summary>
        public static string About_Review {
            get {
                return ResourceManager.GetString("About_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///Source Code: ähnelt.
        /// </summary>
        public static string About_Source_Code {
            get {
                return ResourceManager.GetString("About_Source_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 7Pass Version: {0} ähnelt.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow ähnelt.
        /// </summary>
        public static string AnalyticsSettings_Allow {
            get {
                return ResourceManager.GetString("AnalyticsSettings_Allow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable ähnelt.
        /// </summary>
        public static string AnalyticsSettings_Disable {
            get {
                return ResourceManager.GetString("AnalyticsSettings_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die analytics ähnelt.
        /// </summary>
        public static string AnalyticsSettings_PageTitle {
            get {
                return ResourceManager.GetString("AnalyticsSettings_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 7Pass collects usage information in order to continuously enhance user experience.
        ///
        ///The collection information will never have your database information, or any information that can directly identify you. However:
        ///- 7Pass does collect your installation ID to link information sent from your device together. This changes everytime 7Pass is installed.
        ///- Usage collection uses very little network traffic, but the cost to your bill may add up if you&apos;re on a capped plan.
        ///
        ///The collected information will be ve [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string AnalyticsSettings_Policy {
            get {
                return ResourceManager.GetString("AnalyticsSettings_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string App_About {
            get {
                return ResourceManager.GetString("App_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select DB ähnelt.
        /// </summary>
        public static string App_Databases {
            get {
                return ResourceManager.GetString("App_Databases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        public static string App_Home {
            get {
                return ResourceManager.GetString("App_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear ähnelt.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Demo Database ähnelt.
        /// </summary>
        public static string Download_Demo {
            get {
                return ResourceManager.GetString("Download_Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die add database ähnelt.
        /// </summary>
        public static string Download_PageTitle {
            get {
                return ResourceManager.GetString("Download_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Web Server ähnelt.
        /// </summary>
        public static string Download_Web {
            get {
                return ResourceManager.GetString("Download_Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email ähnelt.
        /// </summary>
        public static string DropBox_Email {
            get {
                return ResourceManager.GetString("DropBox_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        public static string DropBox_Login {
            get {
                return ResourceManager.GetString("DropBox_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string DropBox_Password {
            get {
                return ResourceManager.GetString("DropBox_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die use phone browser ähnelt.
        /// </summary>
        public static string EntryDetails_ExternalBrowser {
            get {
                return ResourceManager.GetString("EntryDetails_ExternalBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fields ähnelt.
        /// </summary>
        public static string EntryDetails_Fields {
            get {
                return ResourceManager.GetString("EntryDetails_Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generate Password ähnelt.
        /// </summary>
        public static string EntryDetails_GeneratePassword {
            get {
                return ResourceManager.GetString("EntryDetails_GeneratePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die use integrated browser ähnelt.
        /// </summary>
        public static string EntryDetails_IntegratedBrowser {
            get {
                return ResourceManager.GetString("EntryDetails_IntegratedBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notes ähnelt.
        /// </summary>
        public static string EntryDetails_Notes {
            get {
                return ResourceManager.GetString("EntryDetails_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die entry ähnelt.
        /// </summary>
        public static string EntryDetails_PageTitle {
            get {
                return ResourceManager.GetString("EntryDetails_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string EntryDetails_Password {
            get {
                return ResourceManager.GetString("EntryDetails_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset Entry ähnelt.
        /// </summary>
        public static string EntryDetails_ResetEntry {
            get {
                return ResourceManager.GetString("EntryDetails_ResetEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Entry ähnelt.
        /// </summary>
        public static string EntryDetails_SaveEntry {
            get {
                return ResourceManager.GetString("EntryDetails_SaveEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title ähnelt.
        /// </summary>
        public static string EntryDetails_Title {
            get {
                return ResourceManager.GetString("EntryDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die URL ähnelt.
        /// </summary>
        public static string EntryDetails_Url {
            get {
                return ResourceManager.GetString("EntryDetails_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User name ähnelt.
        /// </summary>
        public static string EntryDetails_Username {
            get {
                return ResourceManager.GetString("EntryDetails_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string EntryFields_Add {
            get {
                return ResourceManager.GetString("EntryFields_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fields ähnelt.
        /// </summary>
        public static string EntryFields_PageTitle {
            get {
                return ResourceManager.GetString("EntryFields_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear All ähnelt.
        /// </summary>
        public static string EntryNotes_ClearAll {
            get {
                return ResourceManager.GetString("EntryNotes_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die notes ähnelt.
        /// </summary>
        public static string EntryNotes_PageTitle {
            get {
                return ResourceManager.GetString("EntryNotes_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm your password ähnelt.
        /// </summary>
        public static string GlobalPass_Confirm {
            get {
                return ResourceManager.GetString("GlobalPass_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die global password ähnelt.
        /// </summary>
        public static string GlobalPass_PageTitle {
            get {
                return ResourceManager.GetString("GlobalPass_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Global password ähnelt.
        /// </summary>
        public static string GlobalPass_Password {
            get {
                return ResourceManager.GetString("GlobalPass_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set ähnelt.
        /// </summary>
        public static string GlobalPass_Set {
            get {
                return ResourceManager.GetString("GlobalPass_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string GlobalPassVerify_OK {
            get {
                return ResourceManager.GetString("GlobalPassVerify_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die global password ähnelt.
        /// </summary>
        public static string GlobalPassVerify_PageTitle {
            get {
                return ResourceManager.GetString("GlobalPassVerify_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter your password to unlock 7Pass ähnelt.
        /// </summary>
        public static string GlobalPassVerify_Prompt {
            get {
                return ResourceManager.GetString("GlobalPassVerify_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear History List ähnelt.
        /// </summary>
        public static string GroupDetails_ClearHistory {
            get {
                return ResourceManager.GetString("GroupDetails_ClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die delete ähnelt.
        /// </summary>
        public static string GroupDetails_Delete {
            get {
                return ResourceManager.GetString("GroupDetails_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die history ähnelt.
        /// </summary>
        public static string GroupDetails_History {
            get {
                return ResourceManager.GetString("GroupDetails_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die move ähnelt.
        /// </summary>
        public static string GroupDetails_Move {
            get {
                return ResourceManager.GetString("GroupDetails_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Entry ähnelt.
        /// </summary>
        public static string GroupDetails_NewEntry {
            get {
                return ResourceManager.GetString("GroupDetails_NewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Group ähnelt.
        /// </summary>
        public static string GroupDetails_NewGroup {
            get {
                return ResourceManager.GetString("GroupDetails_NewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die rename ähnelt.
        /// </summary>
        public static string GroupDetails_Rename {
            get {
                return ResourceManager.GetString("GroupDetails_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        public static string GroupDetails_Search {
            get {
                return ResourceManager.GetString("GroupDetails_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading ähnelt.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add New ähnelt.
        /// </summary>
        public static string MainPage_AddNew {
            get {
                return ResourceManager.GetString("MainPage_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die clear keyfile ähnelt.
        /// </summary>
        public static string MainPage_ClearKeyfile {
            get {
                return ResourceManager.GetString("MainPage_ClearKeyfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die clear password ähnelt.
        /// </summary>
        public static string MainPage_ClearPassword {
            get {
                return ResourceManager.GetString("MainPage_ClearPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die delete ähnelt.
        /// </summary>
        public static string MainPage_Delete {
            get {
                return ResourceManager.GetString("MainPage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die download keyfile ähnelt.
        /// </summary>
        public static string MainPage_DownloadKeyfile {
            get {
                return ResourceManager.GetString("MainPage_DownloadKeyfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die databases ähnelt.
        /// </summary>
        public static string MainPage_PageTitle {
            get {
                return ResourceManager.GetString("MainPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die pin database ähnelt.
        /// </summary>
        public static string MainPage_Pin {
            get {
                return ResourceManager.GetString("MainPage_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die rename ähnelt.
        /// </summary>
        public static string MainPage_Rename {
            get {
                return ResourceManager.GetString("MainPage_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die settings ähnelt.
        /// </summary>
        public static string MainPage_Settings {
            get {
                return ResourceManager.GetString("MainPage_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die synchronize / update all ähnelt.
        /// </summary>
        public static string MainPage_SyncAll {
            get {
                return ResourceManager.GetString("MainPage_SyncAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Here ähnelt.
        /// </summary>
        public static string MoveTarget_MoveHere {
            get {
                return ResourceManager.GetString("MoveTarget_MoveHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die move to ähnelt.
        /// </summary>
        public static string MoveTarget_PageTitle {
            get {
                return ResourceManager.GetString("MoveTarget_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die generate ähnelt.
        /// </summary>
        public static string PassGen_Generate {
            get {
                return ResourceManager.GetString("PassGen_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Length of generated password ähnelt.
        /// </summary>
        public static string PassGen_Length {
            get {
                return ResourceManager.GetString("PassGen_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die password ähnelt.
        /// </summary>
        public static string PassGen_PageTitle {
            get {
                return ResourceManager.GetString("PassGen_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die results ähnelt.
        /// </summary>
        public static string PassGen_Results {
            get {
                return ResourceManager.GetString("PassGen_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die settings ähnelt.
        /// </summary>
        public static string PassGen_Settings {
            get {
                return ResourceManager.GetString("PassGen_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        public static string Password_Open {
            get {
                return ResourceManager.GetString("Password_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die master key ähnelt.
        /// </summary>
        public static string Password_PageTitle {
            get {
                return ResourceManager.GetString("Password_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Master password ähnelt.
        /// </summary>
        public static string Password_Password {
            get {
                return ResourceManager.GetString("Password_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remember my password ähnelt.
        /// </summary>
        public static string Password_Remember {
            get {
                return ResourceManager.GetString("Password_Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh ähnelt.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die rename ähnelt.
        /// </summary>
        public static string Rename_PageTitle {
            get {
                return ResourceManager.GetString("Rename_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter new name for {0}: ähnelt.
        /// </summary>
        public static string Rename_Prompt {
            get {
                return ResourceManager.GetString("Rename_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename ähnelt.
        /// </summary>
        public static string Rename_Rename {
            get {
                return ResourceManager.GetString("Rename_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die search ähnelt.
        /// </summary>
        public static string Search_PageTitle {
            get {
                return ResourceManager.GetString("Search_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Usage Data Collection ähnelt.
        /// </summary>
        public static string Settings_Analytics {
            get {
                return ResourceManager.GetString("Settings_Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Requires password ähnelt.
        /// </summary>
        public static string Settings_GlobalPass {
            get {
                return ResourceManager.GetString("Settings_GlobalPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide recycle bin ähnelt.
        /// </summary>
        public static string Settings_HideRecycleBin {
            get {
                return ResourceManager.GetString("Settings_HideRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use integrated browser ähnelt.
        /// </summary>
        public static string Settings_IntegratedBrwoser {
            get {
                return ResourceManager.GetString("Settings_IntegratedBrwoser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die settings ähnelt.
        /// </summary>
        public static string Settings_PageTitle {
            get {
                return ResourceManager.GetString("Settings_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Due to SkyDrive limitation, your database has to be renamed to &quot;.doc&quot; extension.
        ///Do you want 7Pass to append &quot;.doc&quot; to your database name and then download it? ähnelt.
        /// </summary>
        public static string SkyDrive_Unsupported {
            get {
                return ResourceManager.GetString("SkyDrive_Unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server requires authentication ähnelt.
        /// </summary>
        public static string WebAuth_Authentication {
            get {
                return ResourceManager.GetString("WebAuth_Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Domain ähnelt.
        /// </summary>
        public static string WebAuth_Domain {
            get {
                return ResourceManager.GetString("WebAuth_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string WebAuth_Password {
            get {
                return ResourceManager.GetString("WebAuth_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User ähnelt.
        /// </summary>
        public static string WebAuth_User {
            get {
                return ResourceManager.GetString("WebAuth_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die detected links ähnelt.
        /// </summary>
        public static string WebBrowse_PageTitle {
            get {
                return ResourceManager.GetString("WebBrowse_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        public static string WebDavDownload_Open {
            get {
                return ResourceManager.GetString("WebDavDownload_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die download ähnelt.
        /// </summary>
        public static string WebDavDownload_PageTitle {
            get {
                return ResourceManager.GetString("WebDavDownload_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string WebDavDownload_Password {
            get {
                return ResourceManager.GetString("WebDavDownload_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database URL ähnelt.
        /// </summary>
        public static string WebDavDownload_Url {
            get {
                return ResourceManager.GetString("WebDavDownload_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        public static string WebDavDownload_Username {
            get {
                return ResourceManager.GetString("WebDavDownload_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        public static string WebDownload_Open {
            get {
                return ResourceManager.GetString("WebDownload_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die download ähnelt.
        /// </summary>
        public static string WebDownload_PageTitle {
            get {
                return ResourceManager.GetString("WebDownload_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database URL ähnelt.
        /// </summary>
        public static string WebDownload_Url {
            get {
                return ResourceManager.GetString("WebDownload_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Go Back ähnelt.
        /// </summary>
        public static string WebView_GoBack {
            get {
                return ResourceManager.GetString("WebView_GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string WebView_Password {
            get {
                return ResourceManager.GetString("WebView_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        public static string WebView_Username {
            get {
                return ResourceManager.GetString("WebView_Username", resourceCulture);
            }
        }
    }
}
